name: Next.js Setup and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and create Next.js app
        run: |
          npx create-next-app@latest my-next-app --use-npm --javascript --tailwind

      - name: List Project Files
        run: |
          cd my-next-app
          ls -laR ./app

      - name: Explicitly set React and React DOM versions to 18.2.0
        run: |
          cd my-next-app
          npm install react@18.2.0 react-dom@18.2.0

      - name: Install Jest, Babel, and Testing Library dependencies
        run: |
          cd my-next-app
          npm install --save-dev jest babel-jest @testing-library/react @testing-library/jest-dom jest-environment-jsdom @babel/core @babel/preset-env @babel/preset-react @babel/preset-typescript

      - name: Install next-auth beta
        run: |
          cd my-next-app
          npm install --save next-auth@beta

      - name: Create an auth.ts file
        run: |
          cd my-next-app
          cat <<EOT > ./auth.ts
          import NextAuth from 'next-auth';
          import Google from "next-auth/providers/google"

          export const { auth, handlers, signIn, signOut } = NextAuth({
            providers: [Google],
          });
          EOT

      - name: Create a footer.tsx component
        run: |
          cd my-next-app
          cat <<EOT > ./footer.tsx
          'use client';

          import Link from 'next/link';
          import { useSession } from 'next-auth/react';

          const Footer = () => {
            const { data: session } = useSession();
            return (
              <footer className="bg-gray-800">
                <div className="container mx-auto px-6 py-4">
                  <div className="flex justify-center">
                    <Link href="https://github.com/nextauthjs/next-auth">
                      <a className="text-gray-400 hover:text-gray-300">
                        Powered by NextAuth
                      </a>
                    </Link>
                  </div>
                </div>
              </footer>
            );
          };
          export default Footer;
          EOT

      - name: List Project Files
        run: |
          cd my-next-app
          ls -la ./

      - name: Display the package.json
        run: |
          cd my-next-app
          cat package.json

      - name: Create Jest and Babel configuration files
        run: |
          cd my-next-app
          cat <<EOT > jest.config.js
          module.exports = {
            testEnvironment: "jsdom",
            collectCoverage: true,
            coverageDirectory: "coverage",
            coverageProvider: "v8",
            transform: {
              "^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
            },
            moduleFileExtensions: ["js", "jsx", "ts", "tsx"],
          };
          EOT

          cat <<EOT > .babelrc
          {
            "presets": ["@babel/preset-env",
            ["@babel/preset-react", { "runtime": "automatic" }],
            "@babel/preset-typescript"]
          }
          EOT

      - name: Set up test file
        run: |
          cd my-next-app
          mkdir -p __tests__
          cat <<EOT > __tests__/index.test.js
          import '@testing-library/jest-dom';
          import React from 'react';
          import { render, screen } from '@testing-library/react';
          import Home from '../app/page';

          test('renders homepage', () => {
            render(<Home />);
            const logo = screen.getByAltText('Next.js logo');
            expect(logo).toBeInTheDocument();
          });
          EOT

      - name: Add npm test script to package.json
        run: |
          cd my-next-app
          npx json -I -f package.json -e 'this.scripts.test="jest -ci"'

      - name: Run tests
        run: |
          cd my-next-app
          npm run test
