name: Next.js Setup and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and create Next.js app
        run: |
          npx create-next-app@latest my-next-app --use-npm --no-ts --no-eslint

      - name: Explicitly set react and react-dom versions to 18.2.0
        run: |
          cd my-next-app
          npm install react@18.2.0 react-dom@18.2.0

      - name: Install jest
        run: |
          cd my-next-app
          npm install --save-dev jest

      - name: Create a jest config file
        run: |
          cd my-next-app
          cat <<EOT > jest.config.js
          module.exports = {
            testEnvironment: "jsdom",
            collectCoverage: true,
            coverageDirectory: "coverage",
            coverageProvider: "v8",
          };
          EOT

      - name: Install testing library
        run: |
          cd my-next-app
          npm install --save-dev @testing-library/react @testing-library/jest-dom

      - name: Set up test configuration and a component to test
        run: |
          cd my-next-app
          mkdir -p __tests__
          cat <<EOT > __tests__/index.test.js
          import { render, screen } from '@testing-library/react';
          import Home from '../pages/index';

          test('renders homepage', () => {
            render(<Home />);
            const heading = screen.getByRole('heading', { name: /welcome to next\\.js!/i });
            expect(heading).toBeInTheDocument();
          });
          EOT

      - name: Run tests
        run: |
          cd my-next-app
          npm run test
